#!/bin/sh
# Created by Sam Gleske
# Generated by Cloneable
# https://github.com/samrocketman/cloneable

JAR_PATH='${jarPath}'
java -jar "\${JAR_PATH}" \\
  ${additional_args} \\
    | xargs -r -n1 -P16 -- git clone --mirror
